# Welcome to Jekyll!

email: jonathan@researchcomputingteams.org
description: Helping managers of RCD and R&D computing teams be more effective and less stressed
title:  Research Computing Teams

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.researchcomputingteams.org"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

sass:
  sass_dir: /assets/sass
  style: compressed
  sourcemap: always

twitter:
  account: "@RCTNewsletter"
  author: "Research Computing Teams"

collections:
  newsletter_issues:
    output: true
    sort_by: date
  interviews:
    output: true
    sort_by: date

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/